version: '3.9'

services:
  django_gunicorn:
    build:
      context: .
    volumes:
      - ./django_project:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
